<Project>
  <PropertyGroup>
    <Version>0.1.15</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultLanguage>en-US</DefaultLanguage>
    <Authors>Get</Authors>
    <PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/GetGet99/QuickMarkup</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup>
  <PackageOutputPath Condition="'$(OS)' == 'Windows_NT'">
    D:\Programming\VS\.LocalNugetPackages
  </PackageOutputPath>

  <PackageOutputPath Condition="'$(OS)' != 'Windows_NT'">
    /mnt/Data/Programming/VS/.LocalNugetPackages
  </PackageOutputPath>
</PropertyGroup>
</Project>
