<Project Sdk="MSTest.Sdk/4.2.3">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickMarkup.Infra\QuickMarkup.Infra.csproj" />
    <ProjectReference Include="..\QuickMarkup.SourceGen\QuickMarkup.SourceGen.csproj" ReferenceOutputAssembly="False" OutputItemType="Analyzer" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**/*.qmui" />
    <AdditionalFiles Include="../QuickMarkup.SourceGen.IntegrationTest/Shared/**/*.qmui" />
    <Compile Include="../QuickMarkup.SourceGen.IntegrationTest/Shared/**/*.cs" />
  </ItemGroup>

</Project>
